// Billing-cycle helpers. A "cycle" is a calendar month, keyed as "YYYY-MM" —
// mirrors the convention used in the frontend's mock dashboardService so
// behaviour stays identical once the frontend is pointed at this API.

export function currentCycleKey(date = new Date()) {
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
}

export function cycleBounds(cycleKey) {
  const [y, m] = cycleKey.split("-").map(Number);
  const start = new Date(Date.UTC(y, m - 1, 1));
  const end = new Date(Date.UTC(y, m, 0, 23, 59, 59));
  return { start, end };
}

export function lastNCycles(n, from = new Date()) {
  const cycles = [];
  for (let i = 0; i < n; i++) {
    const d = new Date(Date.UTC(from.getFullYear(), from.getMonth() - i, 1));
    cycles.push(currentCycleKey(d));
  }
  return cycles;
}

export function wasActiveDuring(tenant, cycleKey) {
  const { start, end } = cycleBounds(cycleKey);
  const moveIn = new Date(tenant.move_in_date);
  const moveOut = tenant.move_out_date ? new Date(tenant.move_out_date) : null;
  if (moveIn > end) return false;
  if (moveOut && moveOut < start) return false;
  return true;
}

// Rent due day for a tenant — the day-of-month their cycle resets on,
// capped at 28 so it's always valid regardless of the current month's
// length. Shared by the dashboard's "upcoming due" list and
// reminderService's send-window calculation.
export function dueDayOf(tenant) {
  return Math.min(new Date(tenant.move_in_date).getDate(), 28);
}

// Classifies a tenant's outcome for one cycle from their raw payment rows
// (already filtered to that tenant + cycle) plus any credit carried in from
// a prior cycle's overpayment. `creditBalance` is the tenant's
// `credit_balance` column *before* this cycle is resolved.
//
// Available funds (this cycle's payments + carried credit) are compared
// against rent due — so a tenant can be fully PAID on zero new payments if
// they're carrying enough credit. `creditApplied` reports how much of that
// carried credit is actually being used to cover this cycle's due amount
// (capped at rentAmount — you can't "apply" more credit than is owed), as
// distinct from `credit`, which is *new* credit generated by this cycle's
// overpayment.
export function classifyCycle(payments, rentAmount, creditBalance = 0) {
  const paid = payments.reduce((sum, p) => sum + Number(p.amount), 0);
  const disputed = payments.some((p) => p.type === "disputed");
  if (disputed) return { status: "DISPUTED", paid, due: rentAmount, balance: 0, credit: 0, creditApplied: 0 };

  const available = paid + creditBalance;
  const creditApplied = Math.min(creditBalance, rentAmount);

  if (available === 0) return { status: "UNPAID", paid, due: rentAmount, balance: rentAmount, credit: 0, creditApplied: 0 };
  if (available < rentAmount) {
    return { status: "PARTIAL", paid, due: rentAmount, balance: rentAmount - available, credit: 0, creditApplied: Math.min(creditBalance, available) };
  }
  if (available === rentAmount) return { status: "PAID", paid, due: rentAmount, balance: 0, credit: 0, creditApplied };
  return { status: "OVERPAID", paid, due: rentAmount, balance: 0, credit: available - rentAmount, creditApplied };
}
